return {
	["package"] = {
		["authors"] = {
			"Not_Lowest",
			"lemonade.gg"
		},
		["description"] = "Agent for making Roblox games.",
		["license"] = "Apache-2.0",
		["name"] = "Codex-rbx/Codex",
		["private"] = true,
		["realm"] = "shared",
		["registry"] = "https://github.com/UpliftGames/wally-index",
		["version"] = "2.1.143",
	},
	["dependencies"] = {
		["Fusion"] = "dervexhero/fusion-03-dev@0.3.0-dev.1",
		["Promise"] = "lukadev-0/typed-promise@4.0.2",
		["Signal"] = "dervexhero/advancedsignal@1.0.1",
		["hashlib"] = "boatbomber/hashlib@^1.0.0",
	},
	["dev-dependencies"] = {
		["TestEZ"] = "roblox/testez@0.4.1",
	},
}
